FROM oven/bun:1

WORKDIR /app

ARG DATABASE_URL

COPY ./package.json ./package.json
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json
COPY ./apps/web  ./apps/web

RUN bun install
RUN bun run generate:db
RUN DARABASE_URL=${DATABASE_URL} bun run build

EXPOSE 3000

CMD [ "bun", "run","start:web"]