name: Deploy frontend to ec2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: Login to Docker
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKER_USERNAME}}
                  password: ${{secrets.DOCKER_PASSWORD}}

            - name: Build and push image to dockerhub
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./Docker/Dockerfile.ws
                  push: true
                  tags: ${{secrets.Docker_USERNAME}}/user-app-frontend:${{github.sha}}
                  build-args: |
                      DATABASE_URL=${{ secrets.DATABASE_URL }}

            - name: Deploy to EC2
              run: |
                  echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
                  chmod 700 /home/runner/ssh_key
                  ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{secrets.HOST}} -t 
                  "docker stop user_frontend || true
                   docker rm user_frontend || true
                    docker run -d -p 3000:3000 --name user_frontend ${{ secrets.DOCKER_USERNAME }}/week-27-turbo-frontend:${{ github.sha }}"
